
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © 2021 Topten Software. All Rights Reserved")]
[assembly: AssemblyVersion("0.1.103")]
[assembly: AssemblyFileVersion("0.1.103")]
[assembly: AssemblyCompany("Topten Software")]
[assembly: AssemblyProduct("nvpatch")]

static class BuildInfo
{
	public static DateTime Date = new DateTime(2021, 8, 31, 0, 30, 53, DateTimeKind.Utc);
}
	